{% set name = "holidays" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 915fdb92b596cfb66067010759b4384a9c6bc82931311d5bf07fe04920cc11bc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - python-dateutil
    - six

test:
  imports:
    - holidays

about:
  home: https://github.com/lidaobing/python-lunardate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Generate and work with holidays in Python'
  description: |
    A fast, efficient Python library for generating country, province and state
    specific sets of holidays on the fly. It aims to make determining whether a
    specific date is a holiday as fast and flexible as possible.

extra:
  recipe-maintainers:
    - bletham
