{% set name = "holidays" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a91324fcaa4c72a0fe9a13601436f65ee33b2ef033686f4e2228d58a7631970

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - six
    - convertdate
    - korean_lunar_calendar

test:
  imports:
    - holidays

about:
  home: https://github.com/dr-prodigy/python-holidays
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate and work with holidays in Python
  description: |
    A fast, efficient Python library for generating country, province and state
    specific sets of holidays on the fly. It aims to make determining whether a
    specific date is a holiday as fast and flexible as possible.

extra:
  recipe-maintainers:
    - bletham
    - rpanai
    - synapticarbors

