travis:
  secure:
    BINSTAR_TOKEN: S6P7pWzCzAHzBjA8A00EfAJWYAumzgX+M/EjVXt5wTigpsu9aoPzgw0Ux6i0s1saNphxMZgIhCh+8D41O81csP7SILrfQDf/CT+CMXz+ZHCHzWSKkjfzc/HV+SYvk+ju6nviN0OYllNRgIPzc3UYEOfLXv1udn+RIGc1nGu00bDtzaCjNobFxOVbxRzHBBsNIeqzBBoF7stFwRVBxsygP1ZfdGhaUTQSGE7n7I7o2s70YokG5dwml/2Gdcbgf3pVUkQV2mhVg2PsQPz3KhARQ2yYFRjZ8e3ok6UriTDRxmLrPpPHb0uD+UUxd313DSzZX+E/MN8WizbiI8MyJltsLkDooVGR+afgEMz2alfqO5bbYALiZIfICFyu2n+VxLPsTsNLZyQ7zZXlnbYbexjxqGAtGVwGTIUOXLyZltwP6HUyQxsDoT1EPy3agLlAFzkNaXZXpVj/7ykcJ1MGEg//HXVsZ14OR94A5pNRCAdU1SZ5jmu7euinQGSdLvCD5PjmuXufy2RFB5iqf11soC8pkxQ6KlsQJs8Vo2N658c/WeTWl2KntYwRr9Jxy1Naq4rn6Zb28/ZDVam4c1TJk6sj3OG/as6DV6O3Z+78tjNM0ZSC8D1R+18xdvmXijVaGX7+mXkMmx/OuHmIUcTZBFwiVLzQgI6OyXgWfAAYgcaVtvw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
